# Generated by Django 6.1 on 2026-08-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('artista', models.CharField(default='Desconhecido', max_length=200)),
                ('arquivo_audio', models.FileField(upload_to='musicas/')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
